name: React ci/cd
on: workflow_dispatch 

jobs:
  Run-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Getcode
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with: 
          node-version: 18

      - name: Run ci test
        run: |
            npm install 
            npm run test

  Build:
    needs: [Run-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout/Getcode
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with: 
          node-version: 18

      - name: build
        run: |
            npm install
            npm run build

      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with: 
          name: Build-Artifact
          path: ./dist

  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploying..."
    
